# Generated by Django 4.1.5 on 2023-01-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postnews",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
