# Generated by Django 4.1.5 on 2023-01-13 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_postnews_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=25, unique=True, verbose_name="Tag name"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="postnews",
            name="tag",
            field=models.ManyToManyField(
                help_text="You can select more than one options", to="news.tag"
            ),
        ),
    ]
