# Generated by Django 4.1.5 on 2023-01-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_tag_postnews_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, verbose_name="URL related name"
            ),
        ),
    ]
