name: PostNews Tests

on:
  push:
    branches:
      - master

  pull_request:    
    branches:
      - master

# on:
#   schedule:
#     - cron: '*/15'      

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Pytest report
      run: |
        pip install pytest
        pip install pytest-django
        pytest -m"not selenium"
    - name: PostNews Testing
      run: |
        python3 manage.py test    

